### ISSUE TITLE
forge test error: Setup failed: Failed to execute command: program not found

### ISSUE THREAD

**Issue by rao261488647** [OpenZeppelin/openzeppelin-foundry-upgrades#12]
[FAIL. Reason: Setup failed: Failed to execute command: program not found] setUp() (gas: 0)

Encountered a total of 1 failing tests, 0 tests succeeded

command：

 forge test  --ffi --match-contract InscriptionUpgradeableTest  --match-test testDeploy

**Comment by ericglau** [comment]
Please provide the entire console output, and if possible, an example repository where this can be reproduced.

From what you have provided so far, this does not look related to this library.  Is forge test working in general for you (e.g. if you do not use this library)?

**Comment by rao261488647** [comment]
my test code ：

`// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {Test, console2} from "forge-std/Test.sol";
import {MyTokenV1} from "../src/MyTokenV1.sol";
import {Upgrades, Options} from "openzeppelin-foundry-upgrades/Upgrades.sol";
import {MyTokenV2} from "../src/MyTokenV2.sol";

contract MyTokenTest is Test {
    MyTokenV1 public myTokenV1;
    MyTokenV2 public myTokenV2;
    address public proxy;
    address owner = 0x64287C27eA4925FfC51D1F3e4f5Fd575e818ee50;

    function setUp() public {
        bytes memory data = abi.encodeCall(MyTokenV1.initialize, owner);
        proxy = Upgrades.deployUUPSProxy("MyTokenV1.sol:MyTokenV1", data);
        myTokenV1 = MyTokenV1(proxy);
    }

    function test_v1_age() public {
        assertEq(myTokenV1.age(), 10);
    }

    function test_v2_age() public {
        Options memory opts;
        opts.referenceContract = "MyTokenV1.sol";
        opts.unsafeSkipAllChecks = false;
        Upgrades.upgradeProxy(
            proxy,
            "MyTokenV2.sol:MyTokenV2",
            "",
            opts,
            owner
        );
        myTokenV2 = MyTokenV2(proxy);
        myTokenV2.setAgeV2(100);
        assertEq(myTokenV2.ageV2(), 100);
    }
}
`
execute command ：
`
forge test -vvvv --ffi --force
`

console log ：

`
Compiler run successful with warnings:
Warning (3420): Source file does not specify required compiler version! Consider adding "pragma solidity ^0.8.20;"
--> lib/openzeppelin-foundry-upgrades/lib/solidity-stringutils/strings.sol

Warning (2018): Function state mutability can be restricted to view
   --> lib/openzeppelin-foundry-upgrades/src/internal/Utils.sol:123:5:
    |
123 |     function getOutDir() internal returns (string memory) {
    |     ^ (Relevant source part starts here and spans across multiple lines).

2024-01-17T15:40:37.915521Z ERROR forge::runner: setUp failed reason="Failed to execute command: program not found" contract=0x7fa9385be102ac3eac297483dd6233d62b3e1496

Running 1 test for test/MyTokenTest.t.sol:MyTokenTest
[FAIL. Reason: Setup failed: Failed to execute command: program not found] setUp() (gas: 0)
Traces:
  [1451024] MyTokenTest::setUp()
    ├─ [0] VM::envOr(FOUNDRY_OUT, out) [staticcall]
    │   └─ ← <env var value>
    ├─ [0] VM::projectRoot() [staticcall]
    │   └─ ← D:/workspace/foundry_wp/testUpgrade
    ├─ [0] VM::readFile(D:/workspace/foundry_wp/testUpgrade/out/MyTokenV1.sol/MyTokenV1.json) [staticcall]
    │   └─ ← <file>
    ├─ [0] VM::parseJsonString(<stringified JSON>, .ast.absolutePath) [staticcall]
    │   └─ ← src/MyTokenV1.sol
    ├─ [0] VM::parseJsonString(<stringified JSON>, .ast.license) [staticcall]
    │   └─ ← MIT
    ├─ [0] VM::parseJsonString(<stringified JSON>, .bytecode.object) [staticcall]
    │   └─ ← 0x60a06040523060805234801561001457600080fd5b5061001d610022565b6100d4565b7ff0c57e16840df040f15088dc2f81fe391c3923bec73e23a9662efc9c229c6a00805468010000000000000000900460ff16156100725760405163f92ee8a960e01b815260040160405180910390fd5b80546001600160401b03908116146100d15780546001600160401b0319166001600160401b0390811782556040519081527fc7f505b2f371ae2175ee4913f4499e1f2633a7b5936321eed1cdaeb6115181d29060200160405180910390a15b50565b6080516114b66100fd6000396000818161082701528181610850015261099101526114b66000f3fe6080604052600436106100fe5760003560e01c806370a0823111610095578063a9059cbb11610064578063a9059cbb146102da578063ad3cb1cc146102fa578063c4d66de81461032b578063dd62ed3e1461034b578063f2fde38b1461036b57600080fd5b806370a0823114610226578063715018a6146102695780638da5cb5b1461027e57806395d89b41146102c557600080fd5b8063262a9dff116100d1578063262a9dff146101bc578063313ce567146101e85780634f1ef286146101fc57806352d1902d1461021157600080fd5b806306fdde0314610103578063095ea7b31461012e57806318160ddd1461015e57806323b872dd1461019c575b600080fd5b34801561010f57600080fd5b5061011861038b565b6040516101259190610fbd565b60405180910390f35b34801561013a57600080fd5b5061014e61014936600461100c565b61044e565b6040519015158152602001610125565b34801561016a57600080fd5b507f52c63247e1f47db19d5ce0460030c497f067ca4cebf71ba98eeadabe20bace02545b604051908152602001610125565b3480156101a857600080fd5b5061014e6101b7366004611036565b610468565b3480156101c857600080fd5b506000546101d69060ff1681565b60405160ff9091168152602001610125565b3480156101f457600080fd5b5060126101d6565b61020f61020a366004611088565b61048e565b005b34801561021d57600080fd5b5061018e6104ad565b34801561023257600080fd5b5061018e61024136600461114a565b6001600160a01b03166000908152600080516020611441833981519152602052604090205490565b34801561027557600080fd5b5061020f6104ca565b34801561028a57600080fd5b507f9016d09d72d40fdae2fd8ceac6b6234c7706214fd39c1cd1e609a0528c199300546040516001600160a01b039091168152602001610125565b3480156102d157600080fd5b506101186104de565b3480156102e657600080fd5b5061014e6102f536600461100c565b61051d565b34801561030657600080fd5b50610118604051806040016040528060058152602001640352e302e360dc1b81525081565b34801561033757600080fd5b5061020f61034636600461114a565b61052b565b34801561035757600080fd5b5061018e610366366004611165565b6106b8565b34801561037757600080fd5b5061020f61038636600461114a565b610702565b7f52c63247e1f47db19d5ce0460030c497f067ca4cebf71ba98eeadabe20bace038054606091600080516020611441833981519152916103ca90611198565b80601f01602080910402602001604051908101604052809291908181526020018280546103f690611198565b80156104435780601f1061041857610100808354040283529160200191610443565b820191906000526020600020905b81548152906001019060200180831161042657829003601f168201915b505050505091505090565b60003361045c818585610745565b60019150505b92915050565b600033610476858285610757565b6104818585856107bd565b60019150505b9392505050565b61049661081c565b61049f826108c1565b6104a982826108c9565b5050565b60006104b7610986565b5060008051602061146183398151915290565b6104d26109cf565b6104dc6000610a2a565b565b7f52c63247e1f47db19d5ce0460030c497f067ca4cebf71ba98eeadabe20bace048054606091600080516020611441833981519152916103ca90611198565b60003361045c8185856107bd565b7ff0c57e16840df040f15088dc2f81fe391c3923bec73e23a9662efc9c229c6a008054600160401b810460ff16159067ffffffffffffffff166000811580156105715750825b905060008267ffffffffffffffff16600114801561058e5750303b155b90508115801561059c575080155b156105ba5760405163f92ee8a960e01b815260040160405180910390fd5b845467ffffffffffffffff1916600117855583156105e457845460ff60401b1916600160401b1785555b61062b604051806040016040528060098152602001684d79546f6b656e563160b81b815250604051806040016040528060048152602001634d544b3160e01b815250610a9b565b61063486610aad565b61063c610abe565b61065d3361064c6012600a6112cc565b610658906127106112db565b610ac6565b6000805460ff1916600a17905583156106b057845460ff60401b19168555604051600181527fc7f505b2f371ae2175ee4913f4499e1f2633a7b5936321eed1cdaeb6115181d29060200160405180910390a15b505050505050565b6001600160a01b0391821660009081527f52c63247e1f47db19d5ce0460030c497f067ca4cebf71ba98eeadabe20bace016020908152604080832093909416825291909152205490565b61070a6109cf565b6001600160a01b03811661073957604051631e4fbdf760e01b8152600060048201526024015b60405180910390fd5b61074281610a2a565b50565b6107528383836001610afc565b505050565b600061076384846106b8565b905060001981146107b757818110156107a857604051637dc7a0d960e11b81526001600160a01b03841660048201526024810182905260448101839052606401610730565b6107b784848484036000610afc565b50505050565b6001600160a01b0383166107e757604051634b637e8f60e11b815260006004820152602401610730565b6001600160a01b0382166108115760405163ec442f0560e01b815260006004820152602401610730565b610752838383610be4565b306001600160a01b037f00000000000000000000000000000000000000000000000000000000000000001614806108a357507f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316610897600080516020611461833981519152546001600160a01b031690565b6001600160a01b031614155b156104dc5760405163703e46dd60e11b815260040160405180910390fd5b6107426109cf565b816001600160a01b03166352d1902d6040518163ffffffff1660e01b8152600401602060405180830381865afa925050508015610923575060408051601f3d908101601f19168201909252610920918101906112f2565b60015b61094b57604051634c9c8ce360e01b81526001600160a01b0383166004820152602401610730565b600080516020611461833981519152811461097c57604051632a87526960e21b815260048101829052602401610730565b6107528383610d22565b306001600160a01b037f000000000000000000000000000000000000000000000000000000000000000016146104dc5760405163703e46dd60e11b815260040160405180910390fd5b33610a017f9016d09d72d40fdae2fd8ceac6b6234c7706214fd39c1cd1e609a0528c199300546001600160a01b031690565b6001600160a01b0316146104dc5760405163118cdaa760e01b8152336004820152602401610730565b7f9016d09d72d40fdae2fd8ceac6b6234c7706214fd39c1cd1e609a0528c19930080546001600160a01b031981166001600160a01b03848116918217845560405192169182907f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e090600090a3505050565b610aa3610d78565b6104a98282610dc1565b610ab5610d78565b61074281610e12565b6104dc610d78565b6001600160a01b038216610af05760405163ec442f0560e01b815260006004820152602401610730565b6104a960008383610be4565b6000805160206114418339815191526001600160a01b038516610b355760405163e602df0560e01b815260006004820152602401610730565b6001600160a01b038416610b5f57604051634a1406b160e11b815260006004820152602401610730565b6001600160a01b03808616600090815260018301602090815260408083209388168352929052208390558115610bdd57836001600160a01b0316856001600160a01b03167f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b92585604051610bd491815260200190565b60405180910390a35b5050505050565b6000805160206114418339815191526001600160a01b038416610c205781816002016000828254610c15919061130b565b90915550610c929050565b6001600160a01b03841660009081526020829052604090205482811015610c735760405163391434e360e21b81526001600160a01b03861660048201526024810182905260448101849052606401610730565b6001600160a01b03851660009081526020839052604090209083900390555b6001600160a01b038316610cb0576002810180548390039055610ccf565b6001600160a01b03831660009081526020829052604090208054830190555b826001600160a01b0316846001600160a01b03167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef84604051610d1491815260200190565b60405180910390a350505050565b610d2b82610e1a565b6040516001600160a01b038316907fbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b90600090a2805115610d70576107528282610e7f565b6104a9610ef5565b7ff0c57e16840df040f15088dc2f81fe391c3923bec73e23a9662efc9c229c6a0054600160401b900460ff166104dc57604051631afcd79f60e31b815260040160405180910390fd5b610dc9610d78565b6000805160206114418339815191527f52c63247e1f47db19d5ce0460030c497f067ca4cebf71ba98eeadabe20bace03610e038482611364565b50600481016107b78382611364565b61070a610d78565b806001600160a01b03163b600003610e5057604051634c9c8ce360e01b81526001600160a01b0382166004820152602401610730565b60008051602061146183398151915280546001600160a01b0319166001600160a01b0392909216919091179055565b6060600080846001600160a01b031684604051610e9c9190611424565b600060405180830381855af49150503d8060008114610ed7576040519150601f19603f3d011682016040523d82523d6000602084013e610edc565b606091505b5091509150610eec858383610f14565b95945050505050565b34156104dc5760405163b398979f60e01b815260040160405180910390fd5b606082610f2957610f2482610f70565b610487565b8151158015610f4057506001600160a01b0384163b155b15610f6957604051639996b31560e01b81526001600160a01b0385166004820152602401610730565b5080610487565b805115610f805780518082602001fd5b604051630a12f52160e11b815260040160405180910390fd5b60005b83811015610fb4578181015183820152602001610f9c565b50506000910152565b6020815260008251806020840152610fdc816040850160208701610f99565b601f01601f19169190910160400192915050565b80356001600160a01b038116811461100757600080fd5b919050565b6000806040838503121561101f57600080fd5b61102883610ff0565b946020939093013593505050565b60008060006060848603121561104b57600080fd5b61105484610ff0565b925061106260208501610ff0565b9150604084013590509250925092565b634e487b7160e01b600052604160045260246000fd5b6000806040838503121561109b57600080fd5b6110a483610ff0565b9150602083013567ffffffffffffffff808211156110c157600080fd5b818501915085601f8301126110d557600080fd5b8135818111156110e7576110e7611072565b604051601f8201601f19908116603f0116810190838211818310171561110f5761110f611072565b8160405282815288602084870101111561112857600080fd5b8260208601602083013760006020848301015280955050505050509250929050565b60006020828403121561115c57600080fd5b61048782610ff0565b6000806040838503121561117857600080fd5b61118183610ff0565b915061118f60208401610ff0565b90509250929050565b600181811c908216806111ac57607f821691505b6020821081036111cc57634e487b7160e01b600052602260045260246000fd5b50919050565b634e487b7160e01b600052601160045260246000fd5b600181815b80851115611223578160001904821115611209576112096111d2565b8085161561121657918102915b93841c93908002906111ed565b509250929050565b60008261123a57506001610462565b8161124757506000610462565b816001811461125d576002811461126757611283565b6001915050610462565b60ff841115611278576112786111d2565b50506001821b610462565b5060208310610133831016604e8410600b84101617156112a6575081810a610462565b6112b083836111e8565b80600019048211156112c4576112c46111d2565b029392505050565b600061048760ff84168361122b565b8082028115828204841417610462576104626111d2565b60006020828403121561130457600080fd5b5051919050565b80820180821115610462576104626111d2565b601f82111561075257600081815260208120601f850160051c810160208610156113455750805b601f850160051c820191505b818110156106b057828155600101611351565b815167ffffffffffffffff81111561137e5761137e611072565b6113928161138c8454611198565b8461131e565b602080601f8311600181146113c757600084156113af5750858301515b600019600386901b1c1916600185901b1785556106b0565b600085815260208120601f198616915b828110156113f6578886015182559484019460019091019084016113d7565b50858210156114145787850151600019600388901b60f8161c191681555b5050505050600190811b01905550565b60008251611436818460208701610f99565b919091019291505056fe52c63247e1f47db19d5ce0460030c497f067ca4cebf71ba98eeadabe20bace00360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbca2646970667358221220106aed8ba4078674a71c8d2f308a6ebd43172a6dbbdc8314e9395b12be77813264736f6c63430008140033
    ├─ [0] VM::ffi([npx, @openzeppelin/upgrades-core@^1.32.3, validate, out/build-info, --contract, src/MyTokenV1.sol:MyTokenV1])
    │   └─ ← "Failed to execute command: program not found"
    └─ ← "Failed to execute command: program not found"

Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 18.51ms
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/MyTokenTest.t.sol:MyTokenTest
[FAIL. Reason: Setup failed: Failed to execute command: program not found] setUp() (gas: 0)

`

**Comment by ericglau** [comment]
Thanks for the details. This looks similar to https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/14. Are you using Windows and Git Bash?

**Comment by rao261488647** [comment]
> Thanks for the details. This looks similar to #14. Are you using Windows and Git Bash?

my os is windows 10

**Comment by rao261488647** [comment]
PS D:\workspace\foundry_wp\testUpgrade> npx @openzeppelin/upgrades-core@^1.32.3 validate out/build-info --contract src/MyTokenV1.sol:MyTokenV1 --requireReference
C:\Users\RP\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\contract-report.js:65
            throw new Error(`The contract ${sourceContract.fullyQualifiedName} does not specify what contract it upgrades from. Add the \`@custom:oz-upgrades-from <REFERENCE_CONTRACT>\` annotation to the contract, or include the reference contract name when running the validate command or function.`);
                  ^

Error: The contract src/MyTokenV1.sol:MyTokenV1 does not specify what contract it upgrades from. Add the `@custom:oz-upgrades-from <REFERENCE_CONTRACT>` annotation to the contract, or include the reference contract name when running the validate command or function.
    at getContractReports (C:\Users\RP\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\contract-report.js:65:19)
    at validateUpgradeSafety (C:\Users\RP\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\validate-upgrade-safety.js:25:70)
    at async main (C:\Users\RP\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate.js:30:24)
    at async run (C:\Users\RP\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\cli.js:6:5)
PS D:\workspace\foundry_wp\testUpgrade> '
