### ISSUE TITLE
'Program not found' while running proxy upgrade on Windows

### ISSUE THREAD

**Issue by zaevlad** [OpenZeppelin/openzeppelin-foundry-upgrades#14]
Hey, thanks for the great repo! 

I got a problem running a `forge test --ffi`

Here is a function in the test file

```
    function testUpgradeability() public {
        // Upgrade the proxy to a new version; MyTokenV2
        Upgrades.upgradeProxy(address(proxy), "MyTokenV2.sol:MyTokenV2", "", owner);
    }
```

and here is what I got in console 

```
[FAIL. Reason: failed to execute command "npx" "@openzeppelin/upgrades-core@^1.32.3" "validate" "out/build-info" "--contract" "src/MyTokenV2.sol:MyTokenV2" "--requireReference": program not found] testUpgradeability() (gas: 1511906)
Test result: FAILED. 1 passed; 1 failed; 0 skipped; finished in 6.03ms
```

How can I fix it? Thanks!

**Comment by ericglau** [comment]
Hi @zaevlad, what OS are you using and what kind of CLI environment?

Can you ensure that you have Node.js installed according to https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades?tab=readme-ov-file#before-running and that `npx` is available from the command line?  e.g. see if this works: `npx --version`

**Comment by zaevlad** [comment]
> Hi @zaevlad, what OS are you using and what kind of CLI environment?
> 
> Can you ensure that you have Node.js installed according to https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades?tab=readme-ov-file#before-running and that `npx` is available from the command line? e.g. see if this works: `npx --version`

My node is v20.11.0, and npx is 10.2.4 

Foundry update also didn't helped

**Comment by ericglau** [comment]
Are you using Windows? Mac?

**Comment by zaevlad** [comment]
> Are you using Windows or Mac? What kind of shell or command prompt?
> 
> Can you try manually running the following from the project directory and share the output:
> 
> ```
> npx @openzeppelin/upgrades-core@^1.32.3 validate out/build-info --contract src/MyTokenV2.sol:MyTokenV2 --requireReference
> ```

Here is what I got

```
Ok to proceed? (y) y
C:\Users\vladz\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\build-info-file.js:123
            throw new error_1.ValidateCommandError(`Build info file ${buildInfoFilePath} is not from a full compilation.`, () => PARTIAL_COMPILE_HELP);
                  ^

ValidateCommandError: Build info file out\build-info\013722d9e9469cd741f1d3ff2599de2b.json is not from a full compilation.

Recompile all contracts with one of the following commands and try again:
If using Hardhat: npx hardhat clean && npx hardhat compile
If using Foundry: forge clean && forge build
    at C:\Users\vladz\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\build-info-file.js:123:19
    at Array.forEach (<anonymous>)
    at checkOutputSelection (C:\Users\vladz\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\build-info-file.js:119:27)
    at readBuildInfo (C:\Users\vladz\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\build-info-file.js:104:13)
    at async getBuildInfoFiles (C:\Users\vladz\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\build-info-file.js:45:12)
    at async validateUpgradeSafety (C:\Users\vladz\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\validate-upgrade-safety.js:22:28)
    at async main (C:\Users\vladz\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate.js:30:24)
    at async run (C:\Users\vladz\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\cli.js:6:5)

Node.js v20.11.0
```

**Comment by ericglau** [comment]
Thanks for the information. It looks like the validate command is working.

Can you try the following and share the output as well?
```
forge test -vvvv --ffi --force
```

**Comment by zaevlad** [comment]
> Thanks for the information. It looks like the validate command is working.
> 
> Can you try the following and share the output as well?
> 
> ```
> forge test -vvvv --ffi --force
> ```

wow, it was big colnsole log

```
[1534912] MyTokenTest::testUpgradeability()
    ├─ [0] VM::startPrank(0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf)
    │   └─ ← ()
    ├─ [0] VM::startPrank(0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf)
    │   └─ ← cannot overwrite a prank until it is applied at least once
    ├─ [0] VM::envOr("FOUNDRY_OUT", "out") [staticcall]
    │   └─ ← <env var value>
    ├─ [0] VM::projectRoot() [staticcall]
    │   └─ ← "C:/Users/vladz/Desktop/Audits/Foundry/Proxy"
    ├─ [0] VM::readFile("C:/Users/vladz/Desktop/Audits/Foundry/Proxy/out/MyTokenV2.sol/MyTokenV2.json") [staticcall]
    │   └─ ← <file>
    ├─ [0] VM::parseJsonString("<stringified JSON>", ".ast.absolutePath") [staticcall]
    │   └─ ← "src/MyTokenV2.sol"
    ├─ [0] VM::parseJsonString("<stringified JSON>", ".ast.license") [staticcall]
    │   └─ ← "MIT"
    ├─ [0] VM::parseJsonString("<stringified JSON>", ".bytecode.object") [staticcall]
    │   └─ ← "0x60a06040523060805234...\long lines of bytes\...170033"
    ├─ [0] VM::ffi(["npx", "@openzeppelin/upgrades-core@^1.32.3", "validate", "out/build-info", "--contract", "src/MyTokenV2.sol:MyTokenV2", "--requireReference"])
    │   └─ ← failed to execute command "npx" "@openzeppelin/upgrades-core@^1.32.3" "validate" "out/build-info" "--contract" "src/MyTokenV2.sol:MyTokenV2" "--requireReference": program not found
    └─ ← failed to execute command "npx" "@openzeppelin/upgrades-core@^1.32.3" "validate" "out/build-info" "--contract" "src/MyTokenV2.sol:MyTokenV2" "--requireReference": program not found

Test result: FAILED. 1 passed; 1 failed; 0 skipped; finished in 17.54ms

Ran 1 test suites: 1 tests passed, 1 failed, 0 skipped (2 total tests)

Failing tests:
Encountered 1 failing test in test/MyTokenTest.t.sol:MyTokenTest
[FAIL. Reason: failed to execute command "npx" "@openzeppelin/upgrades-core@^1.32.3" "validate" "out/build-info" "--contract" "src/MyTokenV2.sol:MyTokenV2" "--requireReference": program not found] testUpgradeability() (gas: 1534912)
```

**Comment by rao261488647** [comment]
PS D:\workspace\foundry_wp\testUpgrade> npx @openzeppelin/upgrades-core@^1.32.3 validate out/build-info --contract src/MyTokenV1.sol:MyTokenV1 --requireReference
C:\Users\RP\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\contract-report.js:65
            throw new Error(`The contract ${sourceContract.fullyQualifiedName} does not specify what contract it upgrades from. Add the \`@custom:oz-upgrades-from <REFERENCE_CONTRACT>\` annotation to the contract, or include the reference contract name when running the validate command or function.`);
                  ^

Error: The contract src/MyTokenV1.sol:MyTokenV1 does not specify what contract it upgrades from. Add the `@custom:oz-upgrades-from <REFERENCE_CONTRACT>` annotation to the contract, or include the reference contract name when running the validate command or function.
    at getContractReports (C:\Users\RP\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\contract-report.js:65:19)
    at validateUpgradeSafety (C:\Users\RP\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\validate-upgrade-safety.js:25:70)
    at async main (C:\Users\RP\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate.js:30:24)
    at async run (C:\Users\RP\AppData\Local\npm-cache\_npx\a80c379185028a0d\node_modules\@openzeppelin\upgrades-core\dist\cli\cli.js:6:5)
PS D:\workspace\foundry_wp\testUpgrade> '
