### ISSUE TITLE
Support use with implementations and proxies from OpenZeppelin Contracts 4.x

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/openzeppelin-foundry-upgrades#2]
Users may want to migrate from Hardhat to Foundry, and they may have contracts and/or proxies already deployed with OpenZeppelin Contracts 4.x.  

This would include:
- [ ] Add support for 4.x UUPS implementations
- [ ] Add support for upgrading existing 4.x proxies

Note that we will probably not support deploying new 4.x proxies, but this feature will cover support for upgrading existing ones.

Originally requested in https://forum.openzeppelin.com/t/first-look-at-the-upcoming-openzeppelin-foundry-upgrades-library/38347/2

**Comment by mrhouzlane** [comment]
What is different from doing this ? 

```solidity
        vm.startBroadcast(deployPrivateKey);
        address implementation = address(new MyContract());
        console2.log(implementation);
        address proxy = address(new ERC1967Proxy(implementation, ""));
        MyContract myContract = MyContract(proxy);
        vm.stopBroadcast();
```

I believe both are using `ERC1967Proxy` contract from OZ, but the call from `Upgrades.sol` contract is more safe?  
Also, here we are initializing a new proxy I believe ? How to use existing proxy with having to call [prepareUpgrade](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/6ef16a6390514e964845fb4740a75071b960320d/src/Upgrades.sol#L366) which have as input a proxy address ?

**Comment by ericglau** [comment]
`prepareUpgrade` is similar to `address(new MyContractV2());` but it also validates the new implementation for upgrade safety as a prerequisite before deploying it.  In order for this to work, in MyContractV2, you should add an annotation to specify the previous version that it upgrades from.  See https://docs.openzeppelin.com/upgrades-plugins/1.x/api-core#define-reference-contracts

Here is an example of how you would then use `prepareUpgrade` and then `upgradeTo` on an existing proxy:
```
        Options memory opts;
        address newImpl = Upgrades.prepareUpgrade("MyContractV2.sol", opts);

        MyContract myContract = MyContract(myProxyAddress);
        myContract.upgradeTo(newImpl);
```

**Comment by mrhouzlane** [comment]
Can  OpenZeppelin/openzeppelin-foundry-upgrades  be installed with a specific version ? 
My contracts are using OZ@v4.9.2 which is incoherent with Upgrades.sol imports using ERC1976Utils, that are not in the Proxy package of OZ@v4.9.2

**Comment by ericglau** [comment]
Right, this issue will need to be fixed in order for 4.x to be used with Upgrades.sol.

To upgrade without `openzeppelin-foundry-upgrades`, it would be like:
```
        address newImpl = address(new MyContract());
        MyContract myContract = MyContract(myProxyAddress);
        myContract.upgradeTo(newImpl);
```

We still recommend validating storage layout compatibility before upgrading.  You can do that using the `validate` command from the [Upgrades CLI](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-core).

**Comment by clauBv23** [comment]
> Note that we will probably not support deploying new 4.x proxies, but this feature will cover support for upgrading existing ones.

Hi there I wonder what is the rationale for this, I'm trying to deploy a new proxy with legacy upgrades and would like to add integration tests for that deployment. Is there a workaround for doing this with the current library?
