### ISSUE TITLE
Error when compiling -  Member "keyExistsJson" not found

### ISSUE THREAD

**Issue by Ramarti** [OpenZeppelin/openzeppelin-foundry-upgrades#33]
Hello,

This is happening in local and github action running script with `Upgrades.deployUUPSProxy`

```
[⠒] Compiling...
[⠒] Compiling 3 files with 0.8.23
[⠑] Solc 0.8.23 finished in 454.43ms
Error: 
Compiler run failed:
Error (9582): Member "keyExistsJson" not found or not visible after argument-dependent lookup in contract Vm.
  --> lib/openzeppelin-foundry-upgrades/src/internal/Utils.sol:83:14:
   |
83 |         if (!vm.keyExistsJson(artifactJson, ".ast")) {
```

[That method should be in VM, as far as I know.](https://book.getfoundry.sh/cheatcodes/key-exists-json?highlight=keyExistsJson#keyexistsjson)

Why is this Utils using vm like this though? Might be related?
```
address constant CHEATCODE_ADDRESS = 0x7109709ECfa91a80626fF3989D68f67F5b1DD12D;
Vm vm = Vm(CHEATCODE_ADDRESS);
```

Thanks for your time

**Comment by ericglau** [comment]
@Ramarti Can you try updating your `forge-std` submodule to v1.8.0 or later? `keyExistsJson` was introduced in [forge-std v1.8.0](https://github.com/foundry-rs/forge-std/releases/tag/v1.8.0).

forge-std v1.8.0 is the minimum required version for this plugin.  I understand this is a breaking change, so we are using semantic versioning to reflect this.  Please see release notes in https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/releases, and I will also update the documentation for this plugin to make this requirement clearer.

**Comment by eddiewong88** [comment]
also experiencing this. tried run `foundryup` but `lib/forge-std/package.json` still shows 1.7.6
any guide on how to update forge-std version easily?

**Comment by ericglau** [comment]
@eddiewong88 You could just cd into the forge-std submodule, use git to checkout the latest tag from the forge-std repo, cd back out and commit.  For example, something like:
```
cd lib/forge-std
git checkout v1.8.1
cd ../..
git add *
git commit -m "Update forge-std"
```
