### ISSUE TITLE
Undisclosed Forge version requirement

### ISSUE THREAD

**Issue by Magicking** [OpenZeppelin/openzeppelin-foundry-upgrades#36]
The Foundry Forge version requirement is unknown. Foundry Forge does not have a versioning scheme, only a git tag.
Therefore, it would be best to know which versions (using dates or commit tags) to understand which version of Foundry Forge is compatible with the plugin.

**Comment by ericglau** [comment]
In v0.2.0 of this plugin (see [Releases](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/releases)), we introduced a requirement on forge-std v1.8.0.  These kinds of requirements are reflected as breaking changes in the changelog and using semantic versioning.  This is the only version requirement that I am aware of -- please let me know if you notice any other unexpected requirement.

I agree the documentation can be improved to make this requirement clearer, and will plan to add that.

**Comment by ericglau** [comment]
Update readme and docs in https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/pull/38 to clarify the above, and this will be included in the docs site via https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/1005
