### ISSUE TITLE
Consider using NPM for distributing this package

### ISSUE THREAD

**Issue by skhomuti** [OpenZeppelin/openzeppelin-foundry-upgrades#40]
This would be a good alternative to default foundry dependency system using git submodules, that is not always using in practice actually

**Comment by ericglau** [comment]
This is available on [Soldeer](https://soldeer.xyz/) which is a [package manager included in Foundry](https://book.getfoundry.sh/projects/soldeer).

See installation steps on https://soldeer.xyz/project/openzeppelin-foundry-upgrades

We'll plan to update the documentation in this repo to include that.

**Comment by masha256** [comment]
+1. It is becoming more popular to use npm instead of foundry for dependencies: https://x.com/PaulRBerg/status/1736695487057531328

**Comment by clauBv23** [comment]
+1, having an npm package would be highly beneficial for projects that already use npm. 

There’s an [open PR](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/pull/73) to include the package version, which is the only missing piece. 

Could you kindly consider moving forward with this?

**Comment by ericglau** [comment]
Thanks for the feedback, everyone.  We agree it makes sense to release this to NPM, but will first need to make some updates to how the package is set up and documentation so that it works with NPM, submodules, and Soldeer installations.

**Comment by ericglau** [comment]
This is available on NPM as [@openzeppelin/foundry-upgrades](https://www.npmjs.com/package/@openzeppelin/foundry-upgrades)
