### ISSUE TITLE
Build file output folder issue

### ISSUE THREAD

**Issue by 0xNarumi** [OpenZeppelin/openzeppelin-foundry-upgrades#5]
I am using the deployUUPSProxy function, but I am encountering an 'Upgrade safety validation failed' error. Looking at the error output, it seems that the build directory is not being recognized. 

```
 throw new error_1.ValidateCommandError(`The directory '${buildInfoDir}' does not exist or does not contain any build info files.`, () => `\\\n              ^\n\nValidateCommandError: The directory 'out/build-info' does not exist or does not contain any build info files.\n\nIf using Foundry, ensure your foundry.toml file has build_info = true.\nCompile your contracts with 'npx hardhat clean && npx hardhat compile' or 'forge clean && forge build' and try again with the correct path to the build info directory.\n 
```

this is my foundry.toml file 

```
[profile.default]
src = "contracts"
out = "foundry-out"
libs = ["node_modules", "lib"]
test = 'test/foundry'
cache_path  = 'forge-cache'
optimizer_runs = 200
solc_version = '0.8.20'
build_info = true
extra_output = ["storageLayout"]
```

As you can see, I have properly set 'build_info' to true in the TOML config file, and 'extra_output' is also configured as specified in the documentation.

Thank you in advance.

**Comment by ericglau** [comment]
Eventually we would want to auto-detect this from foundry.toml.  For now, you can pass in your output directory using the `outDir` option, e.g.:
```
Options memory opts;
opts.outDir = "foundry-out";
address proxy = Upgrades.deployUUPSProxy(
    "MyContract.sol",
    abi.encodeCall(MyContract.initialize, ("arguments for the initialize function")),
    opts
);
```

**Comment by 0xNarumi** [comment]
thanks for the quick reply. 

Then, is `foundry.toml` part that is still specified in the docs not implemented yet?
I am curious about what else that is mentioned in the docs hasn't been implemented yet.

**Comment by ericglau** [comment]
The parts mentioned in the doc are implemented.  What's missing is auto-detection of the `out` setting from foundry.toml -- it's currently just a [TODO here](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/main/src/Upgrades.sol#L451).

**Comment by ericglau** [comment]
@0xNarumi We've made an update in https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/pull/6 which removes the `outDir` option from the Options struct.

You can set `FOUNDRY_OUT=foundry-out` as an environment variable instead, and may need to enable read permissions to that directory.  See the Breaking Changes note in the description of https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/pull/6.
