### ISSUE TITLE
Vm.FfiResult  Identifier not found or not unique

### ISSUE THREAD

**Issue by peitalin** [OpenZeppelin/openzeppelin-foundry-upgrades#55]
Unable to build with fresh install following the instructions and setting remappings.txt 

Appears to be the same issue here:
https://forum.openzeppelin.com/t/not-able-to-build-due-to-vm-ffiresult-not-found/39664/2

**Comment by ericglau** [comment]
This might be a remappings issue. The plugin is simply importing
```
import {Vm} from "forge-std/Vm.sol";
```
and using the `Vm.FfiResult` struct from that. Can you see if you are able to import and use that struct from your own script or test (e.g. if you don't use Foundry Upgrades plugin?)
