### ISSUE TITLE
Upgrading From V1 to V2

### ISSUE THREAD

**Issue by Metaxona** [OpenZeppelin/openzeppelin-foundry-upgrades#62]
I encountered an error upgrading contracts, it says it requires me to state a reference contract, which i did and the upgrade succeeded after.

Now the problem is I am upgrading the same contract in the same implementation file and not creating a copy of the initial implementation and naming it V2, my concern now is does this affect the upgrade check since instead of having the initial contract as reference I am using the same implementation but modified to upgrade an already deployed UUPS contract?

there are no docs that say i need to have a separate v2 contract and use v1 as reference on v2 for upgrades so I am curious and worried that it might affect the contract later specially the states since i don't know if OZ foundry upgrades' storage layout check works on the when the reference contract is the same contract I've altered .

**Comment by ericglau** [comment]
Please see https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/56#issuecomment-2176665117. I'll close this issue, free free to continue the discussion in that other topic if needed.
