### ISSUE TITLE
Error when runnning upgrade safety validation

### ISSUE THREAD

**Issue by clauBv23** [OpenZeppelin/openzeppelin-foundry-upgrades#85]
I carefully followed all the installation and configuration steps, and everything was working perfectly. 

However, it has suddenly started failing with the following error
```
[Revert] revert: Failed to run upgrade safety validation: sh: openzeppelin-upgrades-core: command not found
```

I didn’t upgrade `forge-sdt` or any other library.

**Comment by ericglau** [comment]
Can you try increasing verbosity when running your script/test, and provide the logs?  e.g. `forge script ... -vvv`

**Comment by clauBv23** [comment]
Hey, sorry for the lack of context. 

I'm running a simple test to check the upgrade, the test looks like this:
``` 
function test_validateUpgrade() external {
        Options memory ops;
        ops.referenceContract = "ContractA.sol:ContractA";
        ops.unsafeAllow = "delegatecall";
        Upgrades.validateUpgrade("ContractB.sol", ops);
    }
```

command : `forge test --mt test_validateUpgrade -vvvv` 

and output 
```
[FAIL: revert: Failed to run upgrade safety validation: sh: openzeppelin-upgrades-core: command not found
] 
```

The last logs are: 

```
├─ [0] VM::envOr("OPENZEPPELIN_BASH_PATH", "bash") [staticcall]
│   └─ ← [Return] <env var value>
├─ [0] VM::tryFfi(["bash", "-c", "npx @openzeppelin/upgrades-core@^1.37.0 validate out/build-info --contract src/StagedProposalProcessor.sol:StagedProposalProcessor --reference \"test/utils/harness/DummySPP.sol:DummySPP\" --requireReference --unsafeAllow delegatecall"])
│   └─ ← [Return] (127, 0x, 0x73683a206f70656e7a657070656c696e2d75706772616465732d636f72653a20636f6d6d616e64206e6f7420666f756e640a)
└─ ← [Revert] revert: Failed to run upgrade safety validation: sh: openzeppelin-upgrades-core: command not found

```

and reverts [here](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/16e0ae21e0e39049f619f2396fa28c57fad07368/src/internal/Core.sol#L353)

**Comment by ericglau** [comment]
Thanks for the context.  This might be a local installation issue with the `@openzeppelin/upgrades-core` NPM package which is used for validations.

Can you try reinstalling the package by running
```
npm install @openzeppelin/upgrades-core@latest
```
then try the test again?

**Comment by clauBv23** [comment]
Thanks for the fast response. 

I didn’t have `@openzeppelin/upgrades-core` on my dependencies since I don't use it.

However, after installing it (on my dependencies) seems to work.

But would like to know what is the real issue and why would I need to add `upgrades-core` to my dependencies? Shouldn’t `openzeppelin-foundry-upgrades` dependencies be managed after installing the package?

**Comment by ericglau** [comment]
`openzeppelin-foundry-upgrades` just runs `npx @openzeppelin/upgrades-core...`, and since the `npx` command can fetch the `@openzeppelin/upgrades-core` package to your npm cache, typically there is no need to install it in your dependencies.

In your case, it seems that the fetched package in your local npm cache is somehow missing some files, resulting in the `command not found` error when trying to run a script from the package.  As this occurred on your local environment, I don't know what caused it.

Manually installing the package to your dependencies solves the issue so that `npx` will run it from your installed dependencies.

**Comment by clauBv23** [comment]
I tried installing `openzeppelin-foundry-upgrades` via npm and no longer needed to add `@openzeppelin/upgrades-core` to my dependencies. 

Will keep you posted if this happens again. 

Since this is already solved will close it. 

Thanks @ericglau for your help and fast response.

**Comment by erhant** [comment]
I had the same issue, indeed installing the package manually solves it.

Note that my error was like:

```sh
[FAIL: revert: Failed to run upgrade safety validation: (node:75199) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/modules/cjs/loader:1249
  throw err;
  ^

Error: Cannot find module 'ethereum-cryptography/secp256k1'
Require stack:
- /Users/erhant/.npm/_npx/e9c2fe9985ed1095/node_modules/ethereumjs-util/dist/account.js
- /Users/erhant/.npm/_npx/e9c2fe9985ed1095/node_modules/ethereumjs-util/dist/index.js
- /Users/erhant/.npm/_npx/e9c2fe9985ed1095/node_modules/@openzeppelin/upgrades-core/dist/version.js
- /Users/erhant/.npm/_npx/e9c2fe9985ed1095/node_modules/@openzeppelin/upgrades-core/dist/validate/run.js
- /Users/erhant/.npm/_npx/e9c2fe9985ed1095/node_modules/@openzeppelin/upgrades-core/dist/validate/index.js
- /Users/erhant/.npm/_npx/e9c2fe9985ed1095/node_modules/@openzeppelin/upgrades-core/dist/index.js
... (and so on)
```

so it looks like the package was here but some other package was missing; but in any case installing `@openzeppelin/upgrades-core` solved it
